# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  #  minhshop-app:
  #    image: minhshop
  #    environment:
  #      - _JAVA_OPTIONS=-Xmx512m -Xms512m
  #      - SPRING_PROFILES_ACTIVE=prod,api-docs
  #      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
  #      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
  #      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
  #
  #      - SPRING_DATASOURCE_URL=jdbc:mariadb://minhshop-mariadb:3306/minhshop?useLegacyDatetimeCode=false&serverTimezone=UTC
  #      - SPRING_LIQUIBASE_URL=jdbc:mariadb://minhshop-mariadb:3306/minhshop?useLegacyDatetimeCode=false&serverTimezone=UTC
  #      - JHIPSTER_CACHE_REDIS_SERVER=redis://minhshop-redis:6379
  #      - JHIPSTER_CACHE_REDIS_CLUSTER=false
  #      # - JHIPSTER_CACHE_REDIS_SERVER=redis://minhshop-redis:6379
  #      # - JHIPSTER_CACHE_REDIS_CLUSTER=true
  #      - JHIPSTER_SLEEP=120 # gives time for mariadb server to start
  #      - SPRING_ELASTICSEARCH_REST_URIS=http://minhshop-elasticsearch:9200
  #      - KAFKA_BOOTSTRAPSERVERS=kafka:9092
  #    # If you want to expose these ports outside your dev PC,
  #    # remove the "127.0.0.1:" prefix
  #    ports:
  #      - 30010:8080
  minhshop-mariadb:
    image: mariadb:10.5.8
    #    volumes:
    #      - /root/volumes/jhipster/MinhShop/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=minhshop
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
  minhshop-redis:
    image: redis:6.0.10
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 6379:6379
  minhshop-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    #    volumes:
    #      - /root/volumes/jhipster/MinhShop/elasticsearch/:/usr/share/elasticsearch/data/
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - 'ES_JAVA_OPTS=-Xms256m -Xmx256m'
      - 'discovery.type=single-node'
  kafka:
    image: confluentinc/cp-kafka:5.5.3
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.3
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  jhipster-registry:
    image: jhipster/jhipster-registry:v6.6.0
    volumes:
      - ./central-server-config:/central-config
    # When run with the "dev" Spring profile, the JHipster Registry will
    # read the config from the local filesystem (central-server-config directory)
    # When run with the "prod" Spring profile, it will read the configuration from a Git repository
    # See https://www.jhipster.tech/jhipster-registry/#spring-cloud-config
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=dev,api-docs
      - SPRING_SECURITY_USER_PASSWORD=admin
      - JHIPSTER_REGISTRY_PASSWORD=admin
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/localhost-config/
      # - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=git
      # - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_URI=https://github.com/jhipster/jhipster-registry/
      # - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_PATHS=central-config
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 8761:8761
